[build]
  publish = "."
  command = "node build.js"

[build.environment]
  # These will be automatically set by the Supabase extension
  SUPABASE_DATABASE_URL = "https://xkapxnhwubhfbatekqhz.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYXB4bmh3dWJoZmJhdGVrcWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDE1MTEsImV4cCI6MjA3MzkxNzUxMX0.8GWh7P8ENNZqbH4P0ho6tVspG9tkonS559LoB0t0yjQ"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
